/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class cagcalculate extends javax.swing.JFrame {

    /**
     * Creates new form cagcalculate
     */
    public cagcalculate() {
        initComponents();
    }
    public void open(){
    this.setVisible(true);
    }
    public void close(){
    this.setVisible(false);
    this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Urban Jungle", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("t h e o ry");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 94, 146, 48));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel3.setText("Data Structures ( CSE 2103 )");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 172, 345, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel4.setText("Digital Logic Design ( CSE 2105 )");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 235, 345, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel5.setText("Mathematics - |||   ( MATH 2101 )");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 301, 345, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel6.setText("Electronic Devices & Circuits ( EEE 2141 )");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 365, 345, -1));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel7.setText("Society, Ethics & Technology ( HUM 2109 )");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 437, -1, -1));

        jLabel8.setFont(new java.awt.Font("Urban Jungle", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("s e s s i o n al");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 494, 179, 48));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel9.setText("Data Structures Lab ( CSE 2104 )");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 572, 374, -1));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel10.setText("Digital Logic Design Lab ( CSE 2106 )");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 635, 374, -1));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel11.setText("Electronic Devices & Circuits Lab ( EEE 2142 )");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 697, 374, -1));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel12.setText("Total CGPA:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 840, 200, -1));

        jTextField1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 172, 90, 29));

        jTextField2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextField2.setText("0");
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 231, 90, 29));

        jTextField4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextField4.setText("0");
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 361, 90, 29));

        jTextField5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextField5.setText("0");
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 297, 90, 29));

        jTextField6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextField6.setText("0");
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 433, 90, 29));

        jTextField3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextField3.setText("0");
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 572, 90, 29));

        jTextField7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextField7.setText("0");
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 631, 90, 29));

        jTextField8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextField8.setText("0");
        jPanel2.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 697, 90, 29));

        jTextField9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextField9.setText("0");
        jPanel2.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 761, 90, 29));

        jButton1.setBackground(new java.awt.Color(57, 87, 125));
        jButton1.setFont(new java.awt.Font("Urban Jungle", 0, 19)); // NOI18N
        jButton1.setText("R E S E T");
        jButton1.setActionCommand("reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 840, -1, -1));

        jButton2.setBackground(new java.awt.Color(57, 87, 125));
        jButton2.setFont(new java.awt.Font("Urban Jungle", 0, 19)); // NOI18N
        jButton2.setText("Ca l cu lat e");
        jButton2.setActionCommand("calculate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 840, -1, -1));

        jLabel14.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        jLabel14.setText("Software Development - || (CSE 2100 )");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 765, -1, -1));

        jButton3.setBackground(new java.awt.Color(57, 87, 125));
        jButton3.setFont(new java.awt.Font("Urban Jungle", 0, 19)); // NOI18N
        jButton3.setText("B a c K");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/convophoto.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backbutton.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 520, -1));

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            jTextField1.setText("0");
            jTextField2.setText("0");
            jTextField3.setText("0");
            jTextField4.setText("0");
            jTextField5.setText("0");
            jTextField6.setText("0");
            jTextField7.setText("0");
            jTextField8.setText("0");
            jTextField9.setText("0");
            jLabel12.setText("Total CGPA: ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String s1=jTextField1.getText();  
        String s2=jTextField2.getText();
        String s3=jTextField3.getText();  
        String s4=jTextField4.getText(); 
        String s5=jTextField5.getText();
        String s6=jTextField6.getText(); 
        String s7=jTextField7.getText();
        String s8=jTextField8.getText();
        String s9=jTextField9.getText();
        
        
        float a=Float.parseFloat(s1);
        float b=Float.parseFloat(s2);
        float c=Float.parseFloat(s3);
        float d=Float.parseFloat(s4);
        float e=Float.parseFloat(s5);  
        float f=Float.parseFloat(s6);
        float g=Float.parseFloat(s7);  
        float h=Float.parseFloat(s8);
        float i=Float.parseFloat(s9); 
        float res;
        boolean c1=false;
        boolean c2=false;
        boolean c3=false;
        boolean c4=false;
        boolean c5=false;
        boolean c6=false;
        boolean c7=false;
        boolean c8=false;
        boolean c9=false;
        
        
        ////////////aaaaaaaaaaaaaaaaaaaaaaaaaaaaa////////////////////////////
        if(a>=40 && a<45)
            a=(float)2.00;
        else if(a>=45 && a<50)
            a=(float)2.25;
        else if(a>=50 && a<55)
            a=(float)2.5;
        else if(a>=55 && a<60)
            a=(float)2.75;
        else if(a>=60 && a<65)
            a=(float)3.00;
        else if(a>=65 && a<70)
            a=(float)3.25;
        else if(a>=70 && a<75)
            a=(float)3.5;
        else if(a>=75 && a<80)
            a=(float)3.75;
        else if(a>=80 && a<=100)
            a=(float)4.00;
        else if(a>=0 && a<40)
            a=(float)0.00;
        else c1=true;
        
        //////////////////////////bbbbbbbbbbbbbbbbbbbbbbbbbb//////////////////////////////
        if(b>=40 && b<45)
            b=(float)2.00;
        else if(b>=45 && b<50)
            b=(float)2.25;
        else if(b>=50 && b<55)
            b=(float)2.5;
        else if(b>=55 && b<60)
            b=(float)2.75;
        else if(b>=60 && b<65)
            b=(float)3.00;
        else if(b>=65 && b<70)
            b=(float)3.25;
        else if(b>=70 && b<75)
            b=(float)3.5;
        else if(b>=75 && b<80)
            b=(float)3.75;
        else if(b>=80 && b<=100)
            b=(float)4.00;
        else if(b>=0 && b<40)
            b=(float)0.00;
        else c2=true;
        
        /////////ccccccccccccccccccccccccccccccccccc//////////////////////////////
        
        if(c>=40 && c<45)
            c=(float)2.00;
        else if(c>=45 && c<50)
            c=(float)2.25;
        else if(c>=50 && c<55)
            c=(float)2.5;
        else if(c>=55 && c<60)
            c=(float)2.75;
        else if(c>=60 && c<65)
            c=(float)3.00;
        else if(c>=65 && c<70)
            c=(float)3.25;
        else if(c>=70 && c<75)
            c=(float)3.5;
        else if(c>=75 && c<80)
            c=(float)3.75;
        else if(c>=80 && c<=100)
            c=(float)4.00;
        else if(c>=0 && c<40)
            c=(float)0.00;
        else c3=true;
        
        /////////////////////////dddddddddddddddddddddddddddddddd//////////////////////////////
        
        if(d>=40 && d<45)
            d=(float)2.00;
        else if(d>=45 && d<50)
            d=(float)2.25;
        else if(d>=50 && d<55)
            d=(float)2.5;
        else if(d>=55 && d<60)
            d=(float)2.75;
        else if(d>=60 && d<65)
            d=(float)3.00;
        else if(d>=65 && d<70)
            d=(float)3.25;
        else if(d>=70 && d<75)
            d=(float)3.5;
        else if(d>=75 && d<80)
            d=(float)3.75;
        else if(d>=80 && d<=100)
            d=(float)4.00;
        else if(d>=0 && d<40)
            d=(float)0.00;
        else c4=true;

        
        //////////////////////eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/////////////////////
        
        if(e>=40 && e<45)
            e=(float)2.00;
        else if(e>=45 && e<50)
            e=(float)2.25;
        else if(e>=50 && e<55)
            e=(float)2.5;
        else if(e>=55 && e<60)
            e=(float)2.75;
        else if(e>=60 && e<65)
            e=(float)3.00;
        else if(e>=65 && e<70)
            e=(float)3.25;
        else if(e>=70 && e<75)
            e=(float)3.5;
        else if(e>=75 && e<80)
            e=(float)3.75;
        else if(e>=80 && e<=100)
            e=(float)4.00;
        else if(e>=0 && e<40)
            e=(float)0.00;
        else c5=true;

        
        /////////////////////fffffffffffffffffffff////////////////////////////////
        
        if(f>=40 && f<45)
            f=(float)2.00;
        else if(f>=45 && f<50)
            f=(float)2.25;
        else if(f>=50 && f<55)
            f=(float)2.5;
        else if(f>=55 && f<60)
            f=(float)2.75;
        else if(f>=60 && f<65)
            f=(float)3.00;
        else if(f>=65 && f<70)
            f=(float)3.25;
        else if(f>=70 && f<75)
            f=(float)3.5;
        else if(f>=75 && f<80)
            f=(float)3.75;
        else if(f>=80 && f<=100)
            f=(float)4.00;
        else if(f>=0 && f<40)
            f=(float)0.00;
        else c6=true;

        ///////////////////////gggggggggggggggggggggggggggggggg//////////////////////////////
        
        if(g>=40 && g<45)
            g=(float)2.00;
        else if(g>=45 && g<50)
            g=(float)2.25;
        else if(g>=50 && g<55)
            g=(float)2.5;
        else if(g>=55 && g<60)
            g=(float)2.75;
        else if(g>=60 && g<65)
            g=(float)3.00;
        else if(g>=65 && g<70)
            g=(float)3.25;
        else if(g>=70 && g<75)
            g=(float)3.5;
        else if(g>=75 && g<80)
            g=(float)3.75;
        else if(g>=80 && g<=100)
            g=(float)4.00;
        else if(g>=0 && g<40)
            g=(float)0.00;
        else c7=true;
 
        
       /////////////////////////////////hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh////////////////////
       
       if(h>=40 && h<45)
            h=(float)2.00;
        else if(h>=45 && h<50)
            h=(float)2.25;
        else if(h>=50 && h<55)
            h=(float)2.5;
        else if(h>=55 && h<60)
            h=(float)2.75;
        else if(h>=60 && h<65)
            h=(float)3.00;
        else if(h>=65 && h<70)
            h=(float)3.25;
        else if(h>=70 && h<75)
            h=(float)3.5;
        else if(h>=75 && h<80)
            h=(float)3.75;
        else if(h>=80 && h<=100)
            h=(float)4.00;
        else if(h>=0 && h<40)
            h=(float)0.00;
        else c8=true;

       /////////////////////////iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii//////////////////////////
       
       if(i>=40 && i<45)
            i=(float)2.00;
        else if(i>=45 && i<50)
            i=(float)2.25;
        else if(i>=50 && i<55)
            i=(float)2.5;
        else if(i>=55 && i<60)
            i=(float)2.75;
        else if(i>=60 && i<65)
            i=(float)3.00;
        else if(i>=65 && i<70)
            i=(float)3.25;
        else if(i>=70 && i<75)
            i=(float)3.5;
        else if(i>=75 && i<80)
            i=(float)3.75;
        else if(i>=80 && i<=100)
            i=(float)4.00;
        else if(i>=0 && i<40)
            i=(float)0.00;
        else c9=true;


        
        
        res=(float)((((a+b+c+d+e)*3)+((f+g+h)*1.5+i*.75))/20.25);
        System.out.println(res);
        String result=String.valueOf(res);  
        jLabel12.setText("Total CGPA: "+result);
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        close();
        new MainMenu().open();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cagcalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cagcalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cagcalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cagcalculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cagcalculate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
