
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        databasee.setImageIntoButton(databasee.did, dpMM);
    }
    public void open(){
    this.setVisible(true);
    }
    public void close(){
    this.setVisible(false);
    this.dispose();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        books = new javax.swing.JButton();
        bloodbank = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        reminderButton = new javax.swing.JButton();
        cgcalculate = new javax.swing.JButton();
        notice = new javax.swing.JButton();
        routine = new javax.swing.JButton();
        faculties = new javax.swing.JButton();
        courses = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        dpMM = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        books.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booksmain.jpg"))); // NOI18N
        books.setText("jButton1");
        books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                booksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                booksMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                booksMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                booksMouseReleased(evt);
            }
        });
        getContentPane().add(books, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 150, 180));

        bloodbank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloodBankmainl.jpg"))); // NOI18N
        bloodbank.setText("jButton1");
        bloodbank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bloodbankMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bloodbankMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bloodbankMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bloodbankMouseReleased(evt);
            }
        });
        getContentPane().add(bloodbank, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 150, 180));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoutmain.jpg"))); // NOI18N
        logout.setText("jButton1");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutMouseReleased(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 150, 180));

        reminderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/remindermain.jpg"))); // NOI18N
        reminderButton.setText("jButton1");
        reminderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reminderButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reminderButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reminderButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                reminderButtonMouseReleased(evt);
            }
        });
        reminderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reminderButtonActionPerformed(evt);
            }
        });
        getContentPane().add(reminderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 150, 180));

        cgcalculate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculatecgmain.jpg"))); // NOI18N
        cgcalculate.setText("jButton1");
        cgcalculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cgcalculateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cgcalculateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cgcalculateMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cgcalculateMouseReleased(evt);
            }
        });
        cgcalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgcalculateActionPerformed(evt);
            }
        });
        getContentPane().add(cgcalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 150, 180));

        notice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/noticemain.jpg"))); // NOI18N
        notice.setText("jButton1");
        notice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                noticeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                noticeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                noticeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                noticeMouseReleased(evt);
            }
        });
        notice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noticeActionPerformed(evt);
            }
        });
        getContentPane().add(notice, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 150, 180));

        routine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classroutinemain.jpg"))); // NOI18N
        routine.setText("jButton1");
        routine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                routineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                routineMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                routineMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                routineMouseReleased(evt);
            }
        });
        getContentPane().add(routine, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 150, 180));

        faculties.setIcon(new javax.swing.ImageIcon(getClass().getResource("/facultiesMain.jpg"))); // NOI18N
        faculties.setText("jButton1");
        faculties.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                facultiesFocusLost(evt);
            }
        });
        faculties.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facultiesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facultiesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                facultiesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                facultiesMouseReleased(evt);
            }
        });
        faculties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultiesActionPerformed(evt);
            }
        });
        getContentPane().add(faculties, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 150, 180));

        courses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursesmain.jpg"))); // NOI18N
        courses.setText("jButton1");
        courses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                coursesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                coursesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                coursesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                coursesMouseReleased(evt);
            }
        });
        getContentPane().add(courses, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 180));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 360, 90));

        dpMM.setText("profile");
        dpMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpMMActionPerformed(evt);
            }
        });
        getContentPane().add(dpMM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 120));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 360, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpage.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        new LoginPage().open();
        close();
    }//GEN-LAST:event_logoutActionPerformed

    private void cgcalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgcalculateActionPerformed
        // TODO add your handling code here:
        new cagcalculate().open();
        close();
    }//GEN-LAST:event_cgcalculateActionPerformed

    private void facultiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultiesActionPerformed

    private void reminderButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reminderButtonMousePressed
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/reminderoptional.jpg"));
        reminderButton.setIcon(two);
    }//GEN-LAST:event_reminderButtonMousePressed

    private void reminderButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reminderButtonMouseReleased
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/remindermain.jpg"));
        reminderButton.setIcon(two);
    }//GEN-LAST:event_reminderButtonMouseReleased

    private void reminderButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reminderButtonMouseEntered
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/reminderoptional.jpg"));
        reminderButton.setIcon(two);
    }//GEN-LAST:event_reminderButtonMouseEntered

    private void reminderButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reminderButtonMouseExited
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/remindermain.jpg"));
        reminderButton.setIcon(two);
    }//GEN-LAST:event_reminderButtonMouseExited

    private void reminderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reminderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reminderButtonActionPerformed

    private void coursesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursesMouseEntered
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/coursesoptional.jpg"));
        courses.setIcon(two);
    }//GEN-LAST:event_coursesMouseEntered

    private void coursesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursesMouseExited
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/coursesmain.jpg"));
        courses.setIcon(two);
    }//GEN-LAST:event_coursesMouseExited

    private void coursesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursesMousePressed
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/coursesoptional.jpg"));
        courses.setIcon(two);
    }//GEN-LAST:event_coursesMousePressed

    private void coursesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursesMouseReleased
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/coursesmain.jpg"));
        courses.setIcon(two);
    }//GEN-LAST:event_coursesMouseReleased

    private void facultiesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultiesMouseEntered
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/facultiesoptional.jpg"));
        faculties.setIcon(two);
    }//GEN-LAST:event_facultiesMouseEntered

    private void facultiesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultiesMouseExited
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/facultiesMain.jpg"));
        faculties.setIcon(two);
    }//GEN-LAST:event_facultiesMouseExited

    private void facultiesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultiesMousePressed
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/facultiesoptional.jpg"));
        faculties.setIcon(two);
    }//GEN-LAST:event_facultiesMousePressed

    private void facultiesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultiesMouseReleased
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/facultiesMain.jpg"));
        faculties.setIcon(two);
    }//GEN-LAST:event_facultiesMouseReleased

    private void routineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_routineMouseEntered
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/classroutineoptional.jpg"));
        routine.setIcon(two);
    }//GEN-LAST:event_routineMouseEntered

    private void routineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_routineMouseExited
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/classroutinemain.jpg"));
        routine.setIcon(two);
    }//GEN-LAST:event_routineMouseExited

    private void routineMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_routineMousePressed
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/classroutineoptional.jpg"));
        routine.setIcon(two);
    }//GEN-LAST:event_routineMousePressed

    private void routineMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_routineMouseReleased
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/classroutinemain.jpg"));
        routine.setIcon(two);
    }//GEN-LAST:event_routineMouseReleased

    private void cgcalculateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cgcalculateMouseEntered
        // TODO add your handling code here:
         ImageIcon two = new ImageIcon(getClass().getResource("/calculatecgoptional.jpg"));
        cgcalculate.setIcon(two);
    }//GEN-LAST:event_cgcalculateMouseEntered

    private void cgcalculateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cgcalculateMouseExited
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/calculatecgmain.jpg"));
        cgcalculate.setIcon(two);
    }//GEN-LAST:event_cgcalculateMouseExited

    private void cgcalculateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cgcalculateMousePressed
        // TODO add your handling code here:
         ImageIcon two = new ImageIcon(getClass().getResource("/calculatecgoptional.jpg"));
        cgcalculate.setIcon(two);
    }//GEN-LAST:event_cgcalculateMousePressed

    private void cgcalculateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cgcalculateMouseReleased
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/calculatecgmain.jpg"));
        cgcalculate.setIcon(two);
    }//GEN-LAST:event_cgcalculateMouseReleased

    private void noticeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noticeMouseEntered
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/noticeoptional.jpg"));
        notice.setIcon(two);
    }//GEN-LAST:event_noticeMouseEntered

    private void noticeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noticeMouseExited
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/noticemain.jpg"));
        notice.setIcon(two);
    }//GEN-LAST:event_noticeMouseExited

    private void noticeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noticeMousePressed
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/noticeoptional.jpg"));
        notice.setIcon(two);
    }//GEN-LAST:event_noticeMousePressed

    private void noticeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noticeMouseReleased
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/noticemain.jpg"));
        notice.setIcon(two);
    }//GEN-LAST:event_noticeMouseReleased

    private void booksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksMouseEntered
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/booksoptional.jpg"));
        books.setIcon(two);
    }//GEN-LAST:event_booksMouseEntered

    private void booksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksMouseExited
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/booksmain.jpg"));
        books.setIcon(two);
    }//GEN-LAST:event_booksMouseExited

    private void booksMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksMousePressed
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/booksoptional.jpg"));
        books.setIcon(two);
    }//GEN-LAST:event_booksMousePressed

    private void booksMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksMouseReleased
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/booksmain.jpg"));
        books.setIcon(two);
    }//GEN-LAST:event_booksMouseReleased

    private void bloodbankMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloodbankMouseEntered
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/bloodBankOptional.jpg"));
        bloodbank.setIcon(two);
    }//GEN-LAST:event_bloodbankMouseEntered

    private void bloodbankMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloodbankMouseExited
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/bloodBankmainl.jpg"));
        bloodbank.setIcon(two);
    }//GEN-LAST:event_bloodbankMouseExited

    private void bloodbankMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloodbankMousePressed
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/bloodBankOptional.jpg"));
        bloodbank.setIcon(two);
    }//GEN-LAST:event_bloodbankMousePressed

    private void bloodbankMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloodbankMouseReleased
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/bloodBankmainl.jpg"));
        bloodbank.setIcon(two);
    }//GEN-LAST:event_bloodbankMouseReleased

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/logoutoptional.jpg"));
        logout.setIcon(two);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/logoutmain.jpg"));
        logout.setIcon(two);
    }//GEN-LAST:event_logoutMouseExited

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/logoutoptional.jpg"));
        logout.setIcon(two);
    }//GEN-LAST:event_logoutMousePressed

    private void logoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseReleased
        // TODO add your handling code here:
        ImageIcon two = new ImageIcon(getClass().getResource("/logoutmain.jpg"));
        logout.setIcon(two);
    }//GEN-LAST:event_logoutMouseReleased

    private void facultiesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_facultiesFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_facultiesFocusLost

    private void dpMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpMMActionPerformed
        // TODO add your handling code here:
        new profileshow1().open();
        close();
    }//GEN-LAST:event_dpMMActionPerformed
    
    void hyperlink(String link){
        
        Desktop d = Desktop.getDesktop();
        
        try {
            d.browse(new URI(link));
        } catch (URISyntaxException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void noticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noticeActionPerformed
        // TODO add your handling code here:
        String address = "http://www.aust.edu/news_events.htm";
        hyperlink(address);

    }//GEN-LAST:event_noticeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bloodbank;
    private javax.swing.JButton books;
    private javax.swing.JButton cgcalculate;
    private javax.swing.JButton courses;
    private javax.swing.JButton dpMM;
    private javax.swing.JButton faculties;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logout;
    private javax.swing.JButton notice;
    private javax.swing.JButton reminderButton;
    private javax.swing.JButton routine;
    // End of variables declaration//GEN-END:variables
}
