
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TUSHAR MUHAMMAD
 */
public class SignUpPage2 extends javax.swing.JFrame {

    /**
     * Creates new form SignUpPage1
     */
    String name = "", gender = "", department = "", year = "", semester = "", date = "", contact = "",bday="";

    public SignUpPage2() {
        initComponents();
    }
    public void open(){
    this.setVisible(true);
    }
    public void close(){
    this.setVisible(false);
    this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(540, 750));
        getContentPane().setLayout(null);

        jTextField1.setBackground(new java.awt.Color(57, 87, 125));
        jTextField1.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jTextField1.setText("+880");
        jTextField1.setToolTipText("");
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(200, 600, 300, 23);

        jLabel21.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Date of Birth:");
        jLabel21.setRequestFocusEnabled(false);
        getContentPane().add(jLabel21);
        jLabel21.setBounds(40, 480, 120, 21);

        jLabel22.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Depertment:");
        jLabel22.setRequestFocusEnabled(false);
        getContentPane().add(jLabel22);
        jLabel22.setBounds(40, 520, 90, 21);

        jLabel26.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Name:");
        jLabel26.setRequestFocusEnabled(false);
        getContentPane().add(jLabel26);
        jLabel26.setBounds(40, 400, 90, 21);

        jLabel28.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Semester:");
        jLabel28.setRequestFocusEnabled(false);
        getContentPane().add(jLabel28);
        jLabel28.setBounds(310, 560, 120, 21);

        jLabel31.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("year:");
        jLabel31.setRequestFocusEnabled(false);
        getContentPane().add(jLabel31);
        jLabel31.setBounds(40, 560, 90, 21);

        jLabel32.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Contact no:");
        jLabel32.setRequestFocusEnabled(false);
        getContentPane().add(jLabel32);
        jLabel32.setBounds(40, 600, 140, 21);

        jComboBox4.setBackground(new java.awt.Color(57, 87, 125));
        jComboBox4.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "CSE", "EEE", "Civil", "Architecture", "IPE", "Mechanical" }));
        jComboBox4.setBorder(null);
        jComboBox4.setRequestFocusEnabled(false);
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(200, 520, 300, 23);

        jLabel33.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Gender:");
        jLabel33.setRequestFocusEnabled(false);
        getContentPane().add(jLabel33);
        jLabel33.setBounds(40, 440, 90, 21);

        jComboBox5.setBackground(new java.awt.Color(57, 87, 125));
        jComboBox5.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1st", "2nd", "3rd", "4th" }));
        jComboBox5.setBorder(null);
        jComboBox5.setRequestFocusEnabled(false);
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(200, 560, 90, 23);

        jComboBox6.setBackground(new java.awt.Color(57, 87, 125));
        jComboBox6.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1st", "2nd" }));
        jComboBox6.setBorder(null);
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(410, 560, 90, 23);

        jRadioButton1.setBackground(new java.awt.Color(57, 87, 125));
        jRadioButton1.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jRadioButton1.setText("Male");
        jRadioButton1.setRequestFocusEnabled(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(200, 440, 130, 23);

        jRadioButton2.setBackground(new java.awt.Color(57, 87, 125));
        jRadioButton2.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(370, 440, 130, 23);

        jLabel2.setFont(new java.awt.Font("Urban Jungle", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("P e rsonal   i n fo");
        jLabel2.setRequestFocusEnabled(false);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 339, 240, 31);

        jButton1.setBackground(new java.awt.Color(57, 87, 125));
        jButton1.setFont(new java.awt.Font("Urban Jungle", 0, 19)); // NOI18N
        jButton1.setText("r e g i s t e r");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 660, 120, 30);

        jTextField2.setBackground(new java.awt.Color(57, 87, 125));
        jTextField2.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jTextField2.setBorder(null);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(200, 400, 300, 23);

        jButton2.setBackground(new java.awt.Color(57, 87, 125));
        jButton2.setFont(new java.awt.Font("Urban Jungle", 0, 19)); // NOI18N
        jButton2.setText("b ac k");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 660, 120, 30);
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(470, 480, 30, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signnewpage1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 540, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        year = (String) jComboBox5.getSelectedItem();
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setSelected(false);
        gender = "Female";
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    String s;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        databasee db = new databasee();
        name = jTextField2.getText();
        contact = jTextField1.getText();
        DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
        bday=df.format(jDateChooser2.getDate());
        db.setData(SignUpPage.email, SignUpPage.id, SignUpPage.password, name, gender,bday, department, year, semester, contact);
        //System.out.println(year);
      
        
        close();
        new LoginPage().open();
        
        //System.out.println(df.format(jDateChooser1.getDate()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
        gender = "Male";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        department = (String) jComboBox4.getSelectedItem();
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
        semester = (String) jComboBox6.getSelectedItem();
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        close();
        new SignUpPage().open();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:\
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
