/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TUSHAR MUHAMMAD
 */
public class SignUpPage3 extends javax.swing.JFrame {

    /**
     * Creates new form SignUpPage1
     */
    public SignUpPage3() {
        initComponents();
    }
    public void open(){
    this.setVisible(true);
    }
    public void close(){
    this.setVisible(false);
    this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 750));
        getContentPane().setLayout(null);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 120, 70, 21);

        jLabel12.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Password:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 160, 120, 21);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Confirm Password:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 200, 160, 30);

        jLabel20.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Email:");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(30, 80, 80, 21);

        jTextField1.setBackground(new java.awt.Color(57, 87, 125));
        jTextField1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(200, 630, 240, 28);

        jTextField3.setBackground(new java.awt.Color(57, 87, 125));
        jTextField3.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(150, 120, 220, 28);

        jPasswordField1.setBackground(new java.awt.Color(57, 87, 125));
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(150, 160, 220, 28);

        jPasswordField2.setBackground(new java.awt.Color(57, 87, 125));
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(150, 200, 220, 27);

        jLabel21.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Date of Birth:");
        jLabel21.setRequestFocusEnabled(false);
        getContentPane().add(jLabel21);
        jLabel21.setBounds(40, 480, 90, 21);

        jLabel22.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Depertment:");
        jLabel22.setRequestFocusEnabled(false);
        getContentPane().add(jLabel22);
        jLabel22.setBounds(40, 530, 90, 21);

        jLabel26.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Name:");
        jLabel26.setRequestFocusEnabled(false);
        getContentPane().add(jLabel26);
        jLabel26.setBounds(40, 400, 90, 21);

        jLabel28.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Semester:");
        jLabel28.setRequestFocusEnabled(false);
        getContentPane().add(jLabel28);
        jLabel28.setBounds(200, 580, 120, 21);

        jLabel31.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("year:");
        jLabel31.setRequestFocusEnabled(false);
        getContentPane().add(jLabel31);
        jLabel31.setBounds(40, 580, 90, 21);

        jLabel32.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Contact no:");
        jLabel32.setRequestFocusEnabled(false);
        getContentPane().add(jLabel32);
        jLabel32.setBounds(40, 630, 170, 21);

        jComboBox1.setBackground(new java.awt.Color(57, 87, 125));
        jComboBox1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox1.setRequestFocusEnabled(false);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(170, 480, 70, 30);

        jComboBox2.setBackground(new java.awt.Color(57, 87, 125));
        jComboBox2.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(280, 480, 70, 30);

        jComboBox3.setBackground(new java.awt.Color(57, 87, 125));
        jComboBox3.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2018", "2017", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(370, 470, 80, 30);

        jComboBox4.setBackground(new java.awt.Color(57, 87, 125));
        jComboBox4.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "CSE", "EEE", "Civil", "Architecture", "IPE", "Mechanical", "BBA" }));
        jComboBox4.setRequestFocusEnabled(false);
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(180, 530, 240, 33);

        jLabel33.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Gender:");
        jLabel33.setRequestFocusEnabled(false);
        getContentPane().add(jLabel33);
        jLabel33.setBounds(40, 440, 90, 21);

        jComboBox5.setBackground(new java.awt.Color(57, 87, 125));
        jComboBox5.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "1st", "2nd", "3rd", "4th" }));
        jComboBox5.setRequestFocusEnabled(false);
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(130, 580, 50, 34);

        jComboBox6.setBackground(new java.awt.Color(57, 87, 125));
        jComboBox6.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "1st", "2nd" }));
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(330, 580, 110, 34);

        jRadioButton1.setBackground(new java.awt.Color(57, 87, 125));
        jRadioButton1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton1.setText("Male");
        jRadioButton1.setRequestFocusEnabled(false);
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(200, 440, 110, 35);

        jRadioButton2.setBackground(new java.awt.Color(57, 87, 125));
        jRadioButton2.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(320, 430, 110, 33);

        jLabel1.setFont(new java.awt.Font("Urban Jungle", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("logi n    i n fo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 180, 30);

        jLabel2.setFont(new java.awt.Font("Urban Jungle", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Personal  info");
        jLabel2.setRequestFocusEnabled(false);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 339, 207, 31);

        jButton1.setBackground(new java.awt.Color(57, 87, 125));
        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 670, 150, 33);

        jTextField2.setBackground(new java.awt.Color(57, 87, 125));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(190, 410, 230, 30);

        jTextField5.setBackground(new java.awt.Color(57, 87, 125));
        jTextField5.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(150, 80, 220, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
        new LoginPage().open();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
